name: Markdown Lint and Link Check

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint-markdown:
    name: Lint Markdown Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Run markdownlint
        run: markdownlint "**/*.md"

  check-links:
    name: Check for Broken Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install lychee
        run: |
          curl -sSfL https://github.com/lycheeverse/lychee/releases/download/lychee-v0.19.1/lychee-x86_64-unknown-linux-gnu.tar.gz | tar -xz
          sudo mv lychee /usr/local/bin/

      - name: Run lychee
        run: lychee --verbose "**/*.md"
